version: "3.8"

services:
  openvpn-server:
    image: kylemanna/openvpn
    container_name: openvpn-server
    volumes:
      - ./openvpn-data:/etc/openvpn
    ports:
      - '1194:1194/udp'
    cap_add:
      - NET_ADMIN
    restart: always
